# Generated by Django 5.0.1 on 2024-02-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registertable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=60)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('role', models.CharField(max_length=30)),
                ('profilepicture', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
